Name:           nodejs-mute-stream
Version:        0.0.3
Release:        3%{?dist}
Summary:        Basic pass-through stream, but when muted, the bytes are dropped
BuildArch:      noarch

Group:          System Environment/Libraries
License:        BSD
URL:            https://github.com/isaacs/mute-stream
Source0:        http://registry.npmjs.org/mute-stream/-/mute-stream-%{version}.tgz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

BuildRequires:  nodejs-devel

%description
This is a basic pass-through stream, but when muted, the bytes are
silently dropped, rather than being passed through.

%prep
%setup -q -n package

%build
#nothing to see here, move along

%install
rm -rf %buildroot
mkdir -p %{buildroot}%{nodejs_sitelib}/mute-stream
cp -pr package.json mute.js %{buildroot}%{nodejs_sitelib}/mute-stream

%clean
rm -rf %buildroot

%files
%defattr(-,root,root,-)
%{nodejs_sitelib}/mute-stream
%doc LICENSE README.md

%changelog
* Mon Jan 07 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.3-2
- fix summary, URL
- add no-op build section

* Mon Dec 31 2012 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.3-1
- initial package generated by npm2rpm
