Name:           nodejs-charm
Version:        0.1.0
Release:        1%{?dist}
Summary:        ANSI control sequences for terminal cursor hopping and colors
BuildArch:      noarch

Group:          System Environment/Libraries
#no license file included; "MIT" indicated in package.json
License:        MIT
URL:            https://github.com/substack/node-charm
Source0:        http://registry.npmjs.org/charm/-/charm-%{version}.tgz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

BuildRequires:  nodejs-devel

%description
Uses ANSI control sequences to write colors and cursor positions to terminals.

%prep
%setup -q -n package

%build
#nothing to do

%install
rm -rf %buildroot

mkdir -p %{buildroot}%{nodejs_sitelib}/charm
cp -pr package.json index.js lib %{buildroot}%{nodejs_sitelib}/charm

%nodejs_symlink_deps

%clean
rm -rf %buildroot

%files
%defattr(-,root,root,-)
%{nodejs_sitelib}/charm
%doc README.markdown example

%changelog
* Tue Jan 08 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.1.0-1
- initial package generated by npm2rpm
