Name:           nodejs-yamlish
Version:        0.0.5
Release:        1%{?dist}
Summary:        Parser/encoder for the yamlish format
BuildArch:      noarch

Group:          System Environment/Libraries
#no license file included; "MIT" indicated in package.json
License:        MIT
URL:            https://github.com/isaacs/yamlish
Source0:        http://registry.npmjs.org/yamlish/-/yamlish-%{version}.tgz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

BuildRequires:  nodejs-devel


%description
This is a module to parse the "yamlish" format used to serialize
objects in the TAP format.

It's like yaml, but just a tiny little bit smaller.

%prep
%setup -q -n package

%build
#nothing to do

%install
rm -rf %buildroot

mkdir -p %{buildroot}%{nodejs_sitelib}/yamlish
cp -pr package.json yamlish.js %{buildroot}%{nodejs_sitelib}/yamlish

%nodejs_symlink_deps

%clean
rm -rf %buildroot

%files
%defattr(-,root,root,-)
%{nodejs_sitelib}/yamlish
%doc LICENSE README.md

%changelog
* Tue Jan 08 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.5-1
- initial package generated by npm2rpm
