Name:           nodejs-init-package-json
Version:        0.0.7
Release:        3%{?dist}
Summary:        A node module to get your node module started
BuildArch:      noarch

Group:          System Environment/Libraries
License:        BSD
URL:            https://github.com/isaacs/init-package-json
Source0:        http://registry.npmjs.org/init-package-json/-/init-package-json-%{version}.tgz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

BuildRequires:  nodejs-devel

%description
A node module to get your node module started, by creating its package.json
metadata file.

%prep
%setup -q -n package

%build
#nothing to do

%install
rm -rf %buildroot
mkdir -p %{buildroot}%{nodejs_sitelib}/init-package-json
cp -pr default-input.js init-package-json.js package.json %{buildroot}%{nodejs_sitelib}/init-package-json

%nodejs_symlink_deps

%clean
rm -rf %buildroot

%files
%defattr(-,root,root,-)
%{nodejs_sitelib}/init-package-json
%doc README.md example.js

%changelog
* Sun Jan 13 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.7-3
- use HTTP in Source0 instead of HTTPS

* Tue Jan 08 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.7-2
- add missing build section
- improve description

* Mon Dec 31 2012 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.7-1
- initial package generated by npm2rpm
