Name:           nodejs-form-data
Version:        0.0.6
Release:        2%{?dist}
Summary:        A module to create readable "multipart/form-data" streams
BuildArch:      noarch

Group:          System Environment/Libraries
License:        MIT
URL:            https://github.com/felixge/node-form-data
Source0:        http://registry.npmjs.org/form-data/-/form-data-%{version}.tgz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

BuildRequires:  nodejs-devel

%description
A module to create readable "multipart/form-data" streams.  Can be used to
submit forms and file uploads to other web applications.

%prep
%setup -q -n package

%build
#nothing to do

%install
rm -rf %buildroot
mkdir -p %{buildroot}%{nodejs_sitelib}/form-data
cp -pr package.json lib %{buildroot}%{nodejs_sitelib}/form-data

%clean
rm -rf %buildroot

%files
%defattr(-,root,root,-)
%{nodejs_sitelib}/form-data
%doc License Readme.md

%changelog
* Mon Jan 14 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.6-2
- add missing dist macro to Release

* Thu Jan 10 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.6-1
- new upstream release 0.0.6

* Tue Jan 08 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.5-2
- add missing build section

* Mon Dec 31 2012 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.5-1
- initial package generated by npm2rpm
