Name:           nodejs-retry
Version:        0.6.0
Release:        2%{?dist}
Summary:        Retry strategies for failed operations
BuildArch:      noarch

Group:          System Environment/Libraries
License:        MIT
URL:            https://github.com/felixge/node-retry
Source0:        http://registry.npmjs.org/retry/-/retry-%{version}.tgz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

BuildRequires:  nodejs-devel

%description
Abstraction for exponential and custom retry strategies for failed operations.

%prep
%setup -q -n package

%build
#nothing to do

%install
rm -rf %buildroot
mkdir -p %{buildroot}%{nodejs_sitelib}/retry
cp -pr package.json index.js lib %{buildroot}%{nodejs_sitelib}/retry

%nodejs_symlink_deps

%clean
rm -rf %buildroot

%files
%defattr(-,root,root,-)
%{nodejs_sitelib}/retry
%doc License Readme.md equation.gif example

%changelog
* Tue Jan 08 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.6.0-2
- add missing build section
- fix License tag

* Mon Dec 31 2012 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.6.0-1
- initial package generated by npm2rpm
