Name:           nodejs-couch-login
Version:        0.1.15
Release:        2%{?dist}
Summary:        A module for doing logged-in requests to a couchdb server
BuildArch:      noarch

Group:          System Environment/Libraries
License:        BSD
URL:            https://github.com/isaacs/couch-login
Source0:        http://registry.npmjs.org/couch-login/-/couch-login-%{version}.tgz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

BuildRequires:  nodejs-devel

%description
A module for doing logged-in requests to a couchdb server.

%prep
%setup -q -n package

%nodejs_fixdep request

%build
#nothing to do

%install
rm -rf %buildroot
mkdir -p %{buildroot}%{nodejs_sitelib}/couch-login
cp -pr package.json couch-login.js %{buildroot}%{nodejs_sitelib}/couch-login

%clean
rm -rf %buildroot

%files
%defattr(-,root,root,-)
%{nodejs_sitelib}/couch-login
%doc README.md LICENSE

%changelog
* Tue Jan 08 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.1.15-2
- add missing build section

* Mon Dec 31 2012 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.1.15-1
- initial package generated by npm2rpm
