Name:           nodejs-npmlog
Version:        0.0.2
Release:        2%{?dist}
Summary:        Logger for npm
BuildArch:      noarch

Group:          System Environment/Libraries
License:        BSD
URL:            https://github.com/isaacs/npmlog
Source0:        https://registry.npmjs.org/npmlog/-/npmlog-%{version}.tgz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

BuildRequires:  nodejs-devel

%description
The logger utility that npm uses.

This logger is very basic. It does the logging for npm. It supports custom
levels and colored output.

%prep
%setup -q -n package

%build
#nothing to do

%install
rm -rf %buildroot
mkdir -p %{buildroot}%{nodejs_sitelib}/npmlog
cp -pr package.json log.js %{buildroot}%{nodejs_sitelib}/npmlog

%nodejs_symlink_deps

%clean
rm -rf %buildroots

%files
%defattr(-,root,root,-)
%{nodejs_sitelib}/npmlog
%doc LICENSE README.md example.js

%changelog
* Tue Jan 08 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.2-2
- add missing build section
- minor description improvement

* Mon Dec 31 2012 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.2-1
- initial package generated by npm2rpm
