Name:           nodejs-mime
Version:        1.2.7
Release:        2%{?dist}
Summary:        A comprehensive library for mime-type mapping
BuildArch:      noarch

Group:          System Environment/Libraries
License:        MIT
URL:            https://github.com/broofa/node-mime
Source0:        http://registry.npmjs.org/mime/-/mime-%{version}.tgz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

BuildRequires:  nodejs-devel

%description
Comprehensive MIME type mapping API. Includes all 600+ types and 800+ extensions
defined by the Apache project, plus additional types submitted by the node.js
community.

%prep
%setup -q -n package

%build
#nothing to do

%install
rm -rf %buildroot
mkdir -p %{buildroot}%{nodejs_sitelib}/mime
cp -pr package.json types mime.js %{buildroot}%{nodejs_sitelib}/mime

%clean
rm -rf %buildroot

%files
%defattr(-,root,root,-)
%{nodejs_sitelib}/mime
%doc LICENSE README.md

%changelog
* Tue Jan 08 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 1.2.7-2
- add missing build section
- fix URL

* Mon Dec 31 2012 T.C. Hollingsworth <tchollingsworth@gmail.com> - 1.2.7-1
- initial package generated by npm2rpm
